docs/AboutUs.md, docs/team/zaydmahmud.md
=> Add Zayd's Details

docs/AboutUs.md, docs/team/kwanfaiyew.md
Fix #14 
- Add `kwanFaiYew.md` in `docs/team/`
- Add myself into `AboutUs.md`
=> Add Fai Yew's details in documentation

docs/AboutUs.md, docs/team/minh.md
=> Add Minh's details in Documentation

README.md, docs/index.md
=> Update README.md and product name in index.md

docs/DeveloperGuide.md
There is insufficient use cases to describe all the must-have features in BetterCallTA.
Use cases help us have a general idea of how the operation should flow.
Let's create use cases for all features with high priority.
Since we want to focus on the essentials first, creating use cases only for those with high priority allows us to ensure these must-haves are implemented properly before moving on.
=> Update use cases in DeveloperGuide.md

.gitignore, docs/AboutUs.md, package-lock.json, package.json
Fix Zayd photo in `AboutUs.md`
=> Fix Zayd photo in AboutUs.md

src/main/java/seedu/address/model/person/Course.java
=> Add a class to represent academic courses

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java
#39 Update add command parser and add command, and update `ParserUtil.java` to handle `Course` and `Id`
=> Update add command

src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
=> Add functionality to 'find' to allow searching for substrings and ID

.vscode/settings.json, build.gradle, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/storage/StorageManager.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
=> E refactor everything oh my

src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Fix AddCommandParserTest to follow methods in `CommandParserTestUtil`
=> Fix AddCommandParserTest

src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
=> Add functionality to search for Course names

src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
=> Update the NameContainsKeywordsPredicateTest class

src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
Resolve #79 
@Billy026 I would need your help with `AddressBookParserTest#parseCommand_edit` as there may be some bug related to the edit command or the function with this code!
=> Fix AddressBookParserTest#parseCommand_add

src/test/java/seedu/address/logic/LogicManagerTest.java
The format and examples used in the section on Edit command are
incorrect.
This will confuse the users as to the proper usage of the Edit command.
Let's:
* Update the format of Edit command
* Extract constraints on the format in a warning box
* Update examples
This will allow the user to quickly scan through the points they need,
whether it is the format or why their formatting may not be working.
=> Update User Guide

src/main/java/seedu/address/model/person/Course.java
Courses in NUS can only have the following format: (All letters must be capital)
* Start with 2 or 3 letters,
* Followed by 4 digits,
* Ended by up to (optional) 2 letters.
Fixes #126.
=> Update the validation regex and message constraint

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java
Fixes #130 
Adds alphabetical sorting functionality to the address book. The text command 'sort' now displays the users alphabetically by name.
=> Add Sorting

src/main/java/seedu/address/logic/commands/EditCommand.java
Defensive programming is a requirement for the tP. So let's start to use assertions.
=> Add an assertion

src/main/java/seedu/address/logic/commands/DisplayCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FileCommand.java, src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/Histogram.java, src/main/java/seedu/address/ui/UiManager.java, src/test/java/seedu/address/commons/util/JsonUtilTest.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Updated the output of `file /list` command such that users would know which save file they are currently using.
Fixed checkstyle across all files.
=> Update file command and checkstyle 

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
=> Add notes feature backend logic

src/main/java/seedu/address/logic/commands/ResetRecordsCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Add a command to clear the records of all students in the contact list.
Fixes #161. Unit tests will be added soon.
=> Add ResetRecordsCommand

src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/CourseTest.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/PhoneTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> Fix bugs related to Course

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FileCommand.java, src/main/java/seedu/address/logic/parser/FileCommandParser.java, src/test/java/seedu/address/logic/commands/FileCommandTest.java, src/test/java/seedu/address/logic/parser/FileCommandParserTest.java
The `file` command has several identified alpha bugs. This branch addresses the following issues:
- Fixes #184
- Fixes #186 
- Fixes #185 
UG is updated to reflect the changes to the usage of `file` command.
=> Fix alpha bugs related to File command

README.md, docs/UserGuide.md
Ensure that `UserGuide.md` and `README.md` are up-to-date with the command.
=> Update User Guide and README to contain the command ResetRecords

src/main/java/seedu/address/ui/HelpWindow.java
The link to the User Guide is outdated. Let's update that!
Fixes #215.
=> Update the link to the User Guide in the Help window

src/main/java/seedu/address/logic/commands/ResetRecordsCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/ResetRecordsCommandTest.java
=> ResetRecordsCommand - Add error messages and rewrite test cases

src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
=> Update unit tests for Add command related parsers

docs/UserGuide.md
User Guide has been updated to include references to the 'sort' command.
=> Updated the User Guide to include references to the 'sort' command

build.gradle
=> Update the JAR file name to match our product

src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/GradeTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
Set suitable minimum dimensions for all resizable components of the UI
=> Update GUI Minimum Dimensions

src/main/java/seedu/address/logic/commands/ResetRecordsCommand.java
This method commented out is no longer used, so I remove it.
=> Remove redundant comments

src/main/java/seedu/address/logic/parser/FileCommandParser.java
=> Fix FileCommandParser

src/main/resources/view/MainWindow.fxml
=> Change app title to BetterCallTA

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java
An error message should be shown when a user tries to clear an empty contact list.
Fixes #207.
=> Update ClearCommand to show the error message

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/FindCommand.java
=> Update the 'Find' command messaging

src/main/java/seedu/address/logic/Messages.java
=> fuck this shit

src/main/java/seedu/address/model/person/Grade.java
=> Fix grade check bounds

src/main/java/seedu/address/logic/Messages.java
=> Update find comment

docs/UserGuide.md
=> Update Edit Command and remove some emojis in the UG

docs/UserGuide.md
Fixes #320 
Fixes #298 
Fixes #318 
Updates UG messaging to address what is meant by 'multiple parameter sorting', lack of auto-sorting and rewriting an example for optional commands.
=> Update User Guide 

src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/FileCommandParserTest.java, src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
=> Fixes Bug with Argument Tokenizer

docs/DeveloperGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/UiClassDiagram.puml
Some diagrams in the DG are incorrect.
This may lead readers to believe something that is incorrect.
Let's update these diagrams to the latest changes in our project.
This way all diagrams are up-to-date.
=> Update Developers Guide

docs/DeveloperGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/ModelClassDiagram.puml
There is no template for the Implementation section.
Extracting these diagrams to their own section helps with the
design of the DG.
Let's:
* add a template for the Implementations section
* increase the width of some UML diagrams that were too small
This will help enhance the readability of the DG.
=> Update Developer Guide

docs/DeveloperGuide.md, docs/diagrams/FileLoadSequenceDiagram.puml, docs/diagrams/FileSaveSequenceDiagram.puml
=> Add puml diagrams in DG

docs/DeveloperGuide.md, docs/UserGuide.md
Some diagrams are too small.
This will cause problems in the readability of the DG.
Let's increase the widths of the small diagrams.
This helps to improve readability
=> Update width of diagrams in DG

docs/diagrams/FileLoadSequenceDiagram.puml, docs/diagrams/FileSaveSequenceDiagram.puml
=> Update sequence diagram

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
=> Add sample data when running the app for the first time
